# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 704)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Desktop/Результаты Роскосмоса V/DT05/5-PO-v2/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("font: 57 14pt \"Akrobat\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_row = QtWidgets.QPushButton(self.centralwidget)
        self.add_row.setObjectName("add_row")
        self.gridLayout_2.addWidget(self.add_row, 1, 0, 1, 1)
        self.del_row = QtWidgets.QPushButton(self.centralwidget)
        self.del_row.setObjectName("del_row")
        self.gridLayout_2.addWidget(self.del_row, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 853, 29))
        self.menuBar.setObjectName("menuBar")
        self.data = QtWidgets.QMenu(self.menuBar)
        self.data.setObjectName("data")
        MainWindow.setMenuBar(self.menuBar)
        self.new_2 = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("7273854.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_2.setIcon(icon1)
        self.new_2.setObjectName("new_2")
        self.delete_2 = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("5001199.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_2.setIcon(icon2)
        self.delete_2.setObjectName("delete_2")
        self.save_as = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("7274161.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_as.setIcon(icon3)
        self.save_as.setObjectName("save_as")
        self.report = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("7274140.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.report.setIcon(icon4)
        self.report.setObjectName("report")
        self.jornal = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("5082176.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jornal.setIcon(icon5)
        self.jornal.setObjectName("jornal")
        self.save_file = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("5078942.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_file.setIcon(icon6)
        self.save_file.setObjectName("save_file")
        self.data.addSeparator()
        self.data.addAction(self.save_file)
        self.data.addAction(self.save_as)
        self.data.addAction(self.report)
        self.data.addSeparator()
        self.data.addAction(self.jornal)
        self.menuBar.addAction(self.data.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Приложение"))
        self.add_row.setText(_translate("MainWindow", "Добавить строку"))
        self.del_row.setText(_translate("MainWindow", "Удалить строку"))
        self.data.setTitle(_translate("MainWindow", "Файл"))
        self.new_2.setText(_translate("MainWindow", "Добавить строку"))
        self.delete_2.setText(_translate("MainWindow", "Удалить строку"))
        self.save_as.setText(_translate("MainWindow", "Сохранить как..."))
        self.report.setText(_translate("MainWindow", "Выгрузить как отчет"))
        self.jornal.setText(_translate("MainWindow", "Журнал изменений"))
        self.save_file.setText(_translate("MainWindow", "Сохранить изменения"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
