# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jornal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jornal(object):
    def setupUi(self, jornal):
        jornal.setObjectName("jornal")
        jornal.resize(530, 414)
        jornal.setStyleSheet("font: italic 12pt \"Times Roman\";")
        self.gridLayout = QtWidgets.QGridLayout(jornal)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(jornal)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)

        self.retranslateUi(jornal)
        QtCore.QMetaObject.connectSlotsByName(jornal)

    def retranslateUi(self, jornal):
        _translate = QtCore.QCoreApplication.translate
        jornal.setWindowTitle(_translate("jornal", "Журнал изменений"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jornal = QtWidgets.QWidget()
    ui = Ui_jornal()
    ui.setupUi(jornal)
    jornal.show()
    sys.exit(app.exec_())
